# Generated by Django 4.1.2 on 2022-12-29 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_qr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='qr',
        ),
    ]
